name: CI/CD Pipeline with Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python (for Ansible)
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      # Step 3: Install Ansible
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      # Step 4: Execute the Ansible Playbook
      - name: Execute Playbook
        run: |
          ansible-playbook -i inventory.ini playbook.yml
